version: "1.0"

services:
  app:
    image: ${DOCKER_REGISTRY-}paho-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: develop-stage
    ports:
      - "8888:8080"
    command: /bin/sh -c "yarn && quasar dev -m spa"
